#!/usr/bin/env bash
#  Double the number of webservers
sudo apt-get -y update  && sudo apt-get -y install nginx
config="/etc/nginx/sites-available/default"
# config="$1"
# sudo sh -c "echo 'Hello World!' > /var/www/html/index.html"
# sudo sed -i '/^}$/i \ \nlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.google.com\/;\n\t}' $config
# sudo sed -i '/^}$/i \ \n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\tinternal;\n\t}' $config
sudo sed -i "0,/location \/ {/s/location \/ {/&\n\tadd_header X-Served-By '$HOSTNAME';/" $config
sudo service nginx restart
