#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt update && sudo apt install haproxy -y
sudo sh -c 'echo "\nfrontend FE\n\tbind *:80\n\tdefault_backend BE\n" >> /etc/haproxy/haproxy.cfg'
sudo sh -c 'echo "\nbackend BE\n\tbalance roundrobin\n\tserver server1 100.25.110.123:80 check\n\tserver server2 54.237.47.250:80 check\n" >> /etc/haproxy/haproxy.cfg'
