#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID.

handle_sigterm() {
  echo "I hate the kill command"
  rm /var/run/myscript.pid
  exit 0
}
trap 'handle_sigterm' SIGTERM
echo $$ >  /var/run/myscript.pid

trap "echo Y U no love me?!; exit" SIGINT

while true; do
	echo "To infinity and beyond"
	sleep 3
done

