#!/usr/bin/env bash
# this Bash script that displays Best School 10 times. using while and if.

count=1
while [ $count -le 10 ]
do 
    echo "Best School" 
    if [ $count -eq 9 ]
    then
        echo "hi"
    fi
    
    ((count++))
done