#!/usr/bin/env bash
# Write a Bash script that displays numbers from 1 to 20 and.

count=1
while [ $count -le 20 ]
do
    if [ $count == 4 ]
    then
        echo -e "$count\nbad luck from China"
    elif [ $count == 9 ]
    then
        echo -e "$count\nbad luck from Japan"
    elif [ $count == 17 ]
    then
        echo -e "$count\nbad luck from Italy"
    else
        echo "$count"
    fi
    (( count++ ))
done