#!/usr/bin/env bash
sudo apt update
sudo apt install ufw -y
sudo ufw status verbose
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
# befor you enable make sure that ssh are connect port 22
echo "y" | sudo ufw enable
sudo ufw status verbose
