#!/usr/bin/env bash
# Set the number of workers to gracefully restart
NUM_WORKERS=3

# Send signal to gracefully reload Gunicorn workers
kill -s HUP "$(cat /path/to/gunicorn.pid)"

sleep 5

OLD_WORKERS=$(pgrep -c '[g]unicorn')
if [ "$OLD_WORKERS" -gt "$NUM_WORKERS" ]; then
    sleep 5
fi
pkill -9 -f gunicorn

